spring:
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
    pool:
      initial-size: ${R2DBC_POOL_INITIAL_SIZE:10}
      max-size: ${R2DBC_POOL_MAX_SIZE:50}
  flyway:
    url: ${SPRING_FLYWAY_URL}
    user: ${SPRING_FLYWAY_USER}
    password: ${SPRING_FLYWAY_PASSWORD}
    validate-on-migrate: true
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD}
      ssl:
        enabled: ${REDIS_SSL_ENABLED:false}

springdoc:
  swagger-ui:
    enabled: ${SWAGGER_UI_ENABLED:false}
  api-docs:
    enabled: ${API_DOCS_ENABLED:false}

management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

logging:
  level:
    root: WARN
    com.mralmostcool.tarbook: INFO
